### ISSUE TITLE
FE: Add a job 

### ISSUE THREAD

**Issue by ipopa28** [NagarroLabs/HandyMan#16]
- starting with mock-up in mind create the components for the register page

![image](https://user-images.githubusercontent.com/55707502/80708770-dea17d00-8af4-11ea-8eb8-a09ce3cd77d1.png)

- use validation for input fields 
              - **required fields:** Job Category, Estimated Budget, Start Date, Completion Time Frame, Country, City 
              - Job Name of _at least 10 characters_, Required Skills (_at least one_), Job Description of _at least 30 characters_ )

- confirmation message after the job has been added successfully 

- routes to list of my jobs page (where the one which was just created should appear as well)

- create POST call to backend

- see #15 BE: Add a job

**Comment by VladTM23** [comment]
Closed with commit 311fff8e2af88d4a21f7268e53e9fed9d40ec889
