### ISSUE TITLE
FE: Edit a job

### ISSUE THREAD

**Issue by ipopa28** [NagarroLabs/HandyMan#17]
- create the Edit, Cancel and Save button components 

- "Changes were not saved." message if the Cancel button has been pressed

- confirmation message after the job has been edited and saved successfully 

- routes to the job page (showing its edited version)

- create PUT call to backend

- see #13 BE: Edit a job

**Comment by VladTM23** [comment]
Closed with commit 311fff8e2af88d4a21f7268e53e9fed9d40ec889
