### ISSUE TITLE
FE: Delete a job

### ISSUE THREAD

**Issue by ipopa28** [NagarroLabs/HandyMan#18]
- create the Delete button component

- "Are you sure you want to delete this job?" alert message if the Delete button has been pressed

- confirmation message after the job has been deleted successfully 

- routes to the job page (showing the list without the deleted job)

- create DELETE call to backend

- see #14 BE: Delete a job

**Comment by VladTM23** [comment]
Closed with commit 311fff8e2af88d4a21f7268e53e9fed9d40ec889
