### ISSUE TITLE
FE: Upgrade to HandyMan option

### ISSUE THREAD

**Issue by kassimii** [NagarroLabs/HandyMan#19]
- add Update Profile button to Edit profile page(only if the account does not already have a Handyman account)
- Cancel and Save buttons on page
- open Complete your profile Page
![image](https://user-images.githubusercontent.com/48676780/80738651-0bb65580-8b1e-11ea-8c6c-070046e51b59.png)
- validate input fields
- required fields: Area of Interest, Skills, Experience, City, Country
- confirmation message: "Successfully upgrated to Handyman" on Save button/ "HandyMan profile not created" on Cancel button
- routes to list of jobs
- create POST call to backend
- see #20 BE: Upgrade to HandyMan option

**Comment by VladTM23** [comment]
Closed with commit 3a551ab5b6c436524e691be1e9ff3945d1e9c99e
