### ISSUE TITLE
FE: Edit profile

### ISSUE THREAD

**Issue by kassimii** [NagarroLabs/HandyMan#21]
- create "Edit profile" button in Nav bar
- Cancel and Save buttons 
- "Successfully saved"/"Not saved" messages
- edit Handyman profile button(if Handyman upgrade exists) -> routes to Edit Handyman Profile page
- routes to Job Listing page
- creates PUT call to BE
- see #22 BE: Edit profile

**Comment by VladTM23** [comment]
Closed with commit 3a551ab5b6c436524e691be1e9ff3945d1e9c99e
